name: Check DubTraining Appointment Availability

on:
  schedule:
    # Runs 4x/day at 2:00, 12:00, 17:00, 21:00 UTC
    ### - cron: '0 2,12,17,21 * * *'
    - cron: '27 15,17,19,21,23 * * *'
  workflow_dispatch: {}  # lets you trigger it manually from the Actions tab too
  repository_dispatch: {}

permissions:
  contents: write  # needed so the workflow can commit updated known_dates.json back to the repo

jobs:
  check-availability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests

      - name: Python - Run availability checks for all
        continue-on-error: true
        env:
          # Notify Holloway/Chin GroupMe
          GROUPME_BOT_ID: ${{ secrets.GROUPME_BOT_ID_HOLLOWAYS }}
          STATE_FILE: known_dates.json
          MONTHS_AHEAD: '3'
          
        run: |
          python check_appointments_simple_dates_any.py

      - name: Python - Run availability checks for Jamie
        continue-on-error: true
        env:
          NOTIFY_WEBHOOK_URL: ${{ secrets.NOTIFY_WEBHOOK_URL }}
          GROUPME_BOT_ID: ${{ secrets.GROUPME_BOT_ID_DEVELOPMENT }}
          STATE_FILE: known_dates_jamie.json
          MONTHS_AHEAD: '2'
          COACH_NAME: 'Jamie (7th Grade)'
          CALENDAR_ID: '12864420'
          BOOKING_URL: 'https://dubtraining.as.me/schedule/ad1bb86c/appointment/84360440/calendar/12864420'

        run: |
          python check_appointments_w_times.py

      - name: Python - Run availability checks for Savannah
        continue-on-error: true
        env:
          NOTIFY_WEBHOOK_URL: ${{ secrets.NOTIFY_WEBHOOK_URL }}
          STATE_FILE: known_dates_sav.json
          MONTHS_AHEAD: '2'
          COACH_NAME: 'Savannah (7th Grade)'
          CALENDAR_ID: '12868457'
          BOOKING_URL: 'https://dubtraining.as.me/schedule/ad1bb86c/appointment/84360440/calendar/12868457'

        run: |
          python check_appointments_w_times.py

      - name: Python - Run availability checks for All Coaches
        continue-on-error: true
        env:
          GROUPME_BOT_ID: ${{ secrets.GROUPME_BOT_ID_DEVELOPMENT }}
          STATE_FILE: known_dates_any.json
          MONTHS_AHEAD: '2'
          COACH_NAME: 'DubTraining'
          CALENDAR_ID: 'any'
          BOOKING_URL: 'https://dubtraining.as.me/schedule/ad1bb86c/appointment/84360440'

      - name: Python - Run availability checks for 6th grade
        continue-on-error: true
        env:
          GROUPME_BOT_ID: ${{ secrets.GROUPME_BOT_ID_DEVELOPMENT }}
          STATE_FILE: know_dates_any_6th.json
          MONTHS_AHEAD: '2'
          COACH_NAME: '6th Grade'
          APPOINTMENT_TYPE_ID: '84360481'
          CALENDAR_ID: 'any'
          BOOKING_URL: 'https://dubtraining.as.me/schedule/ad1bb86c/appointment/84360481'


        run: |
          python check_appointments_w_times.py

      - name: StatusCake Push Heartbeat
        env:
          STATUSCAKE_PK: ${{ vars.STATUSCAKE_PK }}
        run: |
          curl "https://push.statuscake.com/?PK=$STATUSCAKE_PK&TestID=8017773"

      - name: Commit updated state file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add known_dates.json
          git add known_dates_jamie.json
          git add known_dates_sav.json
          git add known_dates_any.json
          git add know_dates_*.json
          git diff --cached --quiet || git commit -m "Update known appointment dates [skip ci]"
          git push
