name: TEST Check DubTraining Appointment Availability

on:
  workflow_dispatch: {}  # lets you trigger it manually from the Actions tab too


permissions:
  contents: write  # needed so the workflow can commit updated known_dates.json back to the repo

jobs:
  check-availability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests

      - name: Run availability check
        env:
          # NOTIFY_WEBHOOK_URL: ${{ secrets.NOTIFY_WEBHOOK_URL }}
          STATE_FILE: known_dates_test.json
          MONTHS_AHEAD: '2'
        run: |
          python check_appointments_test.py

      - name: Print state file
        run: |
          echo "Printing known dates file..."
          cat known_dates_test.json
